// "README" — an engineering leader's user manual (how to work with me).
// Public surface: plain voice, specific, affirmative. Six sections. R&D-portfolio thinking
// lives on How I Lead, not here.

export const readme = {
  intro:
    'A short user manual for working with me — how I communicate and decide, what you can expect, how I partner across Product, the business, and customers, and where my edges are. It is meant to shorten the trust-building curve. Treat it as a starting point; I adapt to the people and the situation.',

  sections: [
    {
      heading: 'How I communicate and decide',
      body: 'I default to writing — to separate facts from interpretation, make reasoning visible, and keep decisions from drifting from what is actually happening. Expect written context ahead of significant decisions, and “my read is…” framing that separates what I know from what I am inferring. In person I am calm and direct, and I would rather surface an uncomfortable issue early than let it appear late. On decisions, I try to make the real situation and the choices visible, decide clearly, and say who owns the decision — moving quickly on reversible calls and carefully on irreversible ones. I push decisions to whoever holds the context, favor fewer starts and more finishes, and I change my mind when the evidence changes — I will tell you when I have. My default under pressure is to get quieter and more focused, which can make my urgency less visible. I work to make the priority, owner, decision, and expected pace explicit, including what a new priority displaces. Genuine crises should be rare, not the operating model.',
    },
    {
      heading: 'Feedback and what you can expect',
      body: 'Public confidence, private accountability: I back the team in the room and work the hard things directly and privately. Feedback from me is specific and timely, aimed at the work and the system rather than the person, and paired with what I saw and what I would do — and I value the same directness in return. Tell me when I am wrong or moving too fast; I read direct challenge as a sign of trust.\n\nAs a direct report, you can expect clear expectations, honest feedback, visible credit for your work, room to own your decisions, and enough company, product, customer, and organizational context to exercise sound judgment. I will usually share that context in writing and bring leaders into the problem early, rather than present a decision after the important reasoning has already happened. As a peer, expect respect for your domain, shared accountability, and risks raised early rather than pushed across a boundary. I value ownership of outcomes, candor over comfort, evidence over adjectives, and finishing important work over starting a lot of it.',
    },
    {
      heading: 'How I partner across Product, the business, and customers',
      body:
        'With **Product**, I engage early in the customer problem, not only after requirements are written. I bring technical possibilities, architecture, data, operating cost, and evidence from production, and expect us to shape the investment, scope, and sequencing together. I value shared objectives and key results across Product and Engineering, with clear owners and a roadmap visible to both teams and the broader business.\n\nProduct and technical work belong on the same roadmap. Customer capabilities, platform investments, reliability, security, integration, modernization, and operating improvements all compete for the same capacity and should be prioritized together. That makes tradeoffs explicit and prevents Engineering from maintaining a hidden technical roadmap.\n\n**Finance** should hear about a shift in R&D or infrastructure cost from me early, not find it later in a variance report; expect me to bring a clear forward view into annual planning and budget conversations rather than a defence after the fact. I partner with **People leaders** on organization design, workforce planning, hiring, retention, leadership development, and performance management. In both relationships, I try to surface changes and risks early and build the plan collaboratively.\n\nI lean in with **Sales** when technical credibility can help close an important deal, and with **Customer Success and Support** when a customer needs executive attention or help through a difficult issue. Individual deals should not routinely drive the roadmap, but acceleration can make sense when the underlying need is strategically aligned, broadly applicable, and valuable to other customers. With customers and executive sponsors, expect candor, preparation, and follow-through.',
    },
    {
      heading: 'Incidents and operational accountability',
      body: 'During an incident, expect me to be calm, focused on mitigating customer impact, and driving rapid recovery. I want clear ownership, a shared factual picture, and communication that separates what we know from what we are still investigating. Once service is stable, we examine what happened honestly — the technical and organizational conditions, not individual mistakes — and make the changes that reduce recurrence.',
    },
    {
      heading: 'People, teams, performance, and hiring',
      body:
        'I expect leaders and teams to operate autonomously, with room for their own judgment and style. That autonomy sits within shared standards, metrics, priorities, and a common operating model. Common does not mean identical: teams can adapt practices to their context, but substantially different ways of working make onboarding, cross-team collaboration, and changes to team structure harder. I stay close enough to ask informed questions and correct course when a local optimization could weaken the broader organization.\n\nI separate the person from the problem. A performance gap can come from skill, experience, unclear expectations, weak support, organization design, role fit, or willingness. I look honestly at both skill and will, offer real support where improvement is possible, and then make a decision rather than let ambiguity persist. No one should first hear about a material performance problem in a formal review. High standards and dignity are compatible.\n\nI prefer to develop leaders internally when they are willing to grow, dig into hard problems, and take ownership beyond their current role. I hire externally when the organization needs capability or readiness we do not yet have.',
    },
    {
      heading: 'My edges, and how to work well with me',
      body: 'A few edges I already know about:\n\n- I prefer to develop leaders internally when someone wants the responsibility, takes ownership, and has shown the judgment and learning capacity to grow into it. That builds durable capability, but I can wait too long for an internal path to emerge. Push me when the organization needs experience we should hire from outside.\n- I repair systems instinctively, so I can step in too early with an answer. My better role is usually to make the context, constraints, and standards clear, ask informed questions, and let the leader closest to the work shape the solution. Tell me when I am solving a problem that I should be helping someone else own.\n\nTo work well with me: bring the real problem, what is getting in the way, and your read — not a pre-sanitized version. Be clear about what is decided versus still open, and tell me what you actually need: a decision, a sounding board, air cover, or just to be kept informed. Assume good intent, and I will do the same.',
    },
  ],
} as const;
